-- [Reset] 기존 테이블 삭제 (순서 중요: 의존성 역순)
drop table if exists v3_sms_logs;
drop table if exists v3_message_templates;
drop table if exists v3_reservations;
drop table if exists v3_accommodations;

-- [1] 숙소 목록 테이블
create table v3_accommodations (
  name text primary key
);

-- 초기 숙소 데이터
insert into v3_accommodations (name) values
  ('숙소1'),
  ('숙소2'),
  ('공통메세지'),
  ('전체공용');

-- [2] 메시지 템플릿 테이블
create table v3_message_templates (
  id bigint generated by default as identity primary key,
  accommodation_name text references v3_accommodations(name) on delete cascade not null,
  trigger_type text not null, 
  send_time time not null,
  content text not null,
  subject text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- [중요] Upsert 처리를 위한 유니크 제약조건
  unique (accommodation_name, trigger_type)
);

-- [3] 예약 정보 테이블
create table v3_reservations (
  id bigint generated by default as identity primary key,
  guest_name text not null,
  phone_number text not null,
  accommodation_name text references v3_accommodations(name) on delete cascade not null,
  checkin_date date not null,
  checkout_date date not null,
  memo text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- [4] 문자 발송 이력 테이블 (중복 방지용)
create table v3_sms_logs (
  id bigint generated by default as identity primary key,
  reservation_id bigint references v3_reservations(id) on delete cascade not null,
  trigger_type text not null,
  sent_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- [변경] sent_at::date 캐스팅 인덱스 대신 별도 컬럼 사용 (가장 확실한 방법)
  sent_date date not null default current_date,                         
  status text default 'success',
  
  -- [중요] "예약ID + 트리거 + 날짜" 조합은 유일해야 함 (중복 발송 원천 차단)
  unique (reservation_id, trigger_type, sent_date)
);
